### PR TITLE
Play integration

### PR DESCRIPTION
**Pull request by merlinND**

### CODE REVIEW

**Comment by merlinND** [comment]
I see a lot of promising things in there!
It's great you wrote a few tests as well.

Just a couple of questions:
- I saw you committed `activator-launch-1.2.12.jar`, is there any easy way not to have binary committed?
- I think the tests are failing because you made changes after writing them and forgot to update them, should be easy to fix.
- Since other branches have made changes (and most importantly, renames) on files which have been moved in your app, we are likely to run into conflicts. Any idea on how to handle this well?

**Comment by liufengyun** [comment]
Thanks for this commit, we're a step closer to our web GUI goal.

Regarding the commit, I'm thinking if it's possible to encapsulate a web server within an actor, this is the most friendly approach for users of the system. It would be nice if the web server is just an actor component, so that users can choose whether to use the component in a given scenario or not.

**Comment by eliasschegg** [comment]
@merlinND Thanks for the feedback. I was extremely busy today but I'll fix it tomorrow if that's ok
- I didn't intend to add the activator binary to the commit and we don't need it anyways. I'll remove it :)
- You are right about the tests, I'll fix that as well
- The easiest way to proceed is probably to merge everything else first and then I can do another pull and fix things on my side

@liufengyun 
Play is built on top of the Akka framework, but it's not running as a single actor and I don't think that's even possible. However, the frontend is already separated in a different way from the trading simulation backend since I changed the build definition to a multi-project build. Users can simply run `sbt "project ts" run` to start the backend and `sbt "project frontend" run` to start the frontend.

**Comment by liufengyun** [comment]
I see Play seems to be a huge monster. What about other micro - frameworks
in Scala? If we can start and stop the web server from an actor component ,
it's OK as well, no need for the web app itself to be an actor extending
Component.

It seems that if we write a web server from the basic network API, it's
possible. Maybe we can investigate if there are existent micro - frameworks
that fit our purpose.

**Comment by merlinND** [comment]
@liufengyun: I understand your concern. It is true that Play is a full-featured framework. However, we actually need quite a lot of those features (HTTP server, routing, templating, communication with other actors, etc).
Elias was responsible for investigating web frameworks, and since he chose Play I believe it was the most adapted. @eliasschegg, did you run across smaller frameworks which could have been adapted?

As to re-developping our own server from the network API... I think it's way out of the scope of our project :smiley: 

Most importantly, the pragmatic argument would be that the integration with Play has already been implemented by Elias and the PR is ready to merge.

**Comment by liufengyun** [comment]
I just point out the problem from end user's perspective -- if it's a technical difficulty, I'm OK with what we have now.

**Comment by merlinND** [comment]
Hopefully we will make it so that the user doesn't really see the difference :)

**Comment by eliasschegg** [comment]
@liufengyun @merlinND  In terms of lightweight frameworks, I came across [Spray](http://spray.io/) and [Scalatra](http://www.scalatra.org/) among others. 
Spray is mainly just an HTTP server and would have required us to evaluate additional libraries to get features such as templating that are included by default in Play. As a side note, future versions of Play will include Spray HTTP as an alternative to the current Netty HTTP server.
I actually considered Scalatra for a while but Play seemed like the more mature choice with better documentation and a bigger community behind it, which also means that it's easier to find help if your stuck.

@liufengyun Wouldn't we have exactly the same situation from an end user's perspective with any other framework? The choice of the framework is only relevant for people working on visualization but for everyone else there shouldn't be any difference..

**Comment by liufengyun** [comment]
Thanks for the information @eliasschegg.

Currently our users(programmers) just create new instances of components,
and connect them. It would be nice if the web integration will keep the
convention unchanged. I'm thinking Web UI nothing different from the
component Printer. However, since this is difficult to achieve, I'm happy
with what we have now.

2015-03-27 14:58 GMT+01:00 eliasschegg notifications@github.com:

**Pull request merged**
